services:
  postgres:
    image: postgres:15.3-alpine
    container_name: uc-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - uc-backend

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: uc-api-dev
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      # Monte le code source pour que air détecte les changements
      - ./backend:/app
      # Cache des modules Go (évite de re-télécharger à chaque rebuild)
      - go_mod_cache:/root/go/pkg/mod
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - uc-backend
      - uc-api

  frontend:
    build:
      context: ./frontend
    container_name: uc-front-dev
    volumes:
      # Monte le code source pour que Vite détecte les changements
      - ./frontend:/app
      # node_modules isolé dans le conteneur (évite les conflits host/conteneur)
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - uc-api

volumes:
  go_mod_cache:

networks:
  uc-backend:
  uc-api:
