services:
  postgres:
    image: postgres:18.3-alpine
    container_name: uc-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/seeds:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT}:5432"
    networks:
      - uc-backend

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jensentuang/upcycleconnect-api:latest
    container_name: uc-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    networks:
      - uc-api
      - uc-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jensentuang/upcycleconnect-frontend:latest
    container_name: uc-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - uc-api
volumes:
  postgres_data:

networks:
  uc-backend:
  uc-api:
