services:
  postgres:
    image: postgres:15.3-alpine
    container_name: uc-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/seeds:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - uc-backend

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: uc-api-dev
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./backend:/app
      - go_mod_cache:/root/go/pkg/mod
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - uc-backend
      - uc-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: uc-front-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - uc-api

volumes:
  postgres_data_dev:
  go_mod_cache:

networks:
  uc-backend:
  uc-api:
